language: node_js
services:
  - docker
node_js:
  - "8"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
script:
  - yarn test
